--- !ditz.rubyforge.org,2008-03-06/project 
name: strokedb
version: "0.1"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: Storage
- !ditz.rubyforge.org,2008-03-06/component 
  name: General
- !ditz.rubyforge.org,2008-03-06/component 
  name: Meta
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: v0.0.2
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-04-05 16:57:44.086164 Z
    - Yurii Rashkovskii <yrashk@issuesdone.com>
    - created
    - ""
